export const attributesToRemove = [
  'seo_title',
  'seo_sub_text',
  'about_me',
  'course_types',
  'courses_cnt',
  'education',
  'experience',
  'gallery',
  'min_hourly_rate',
  'convict',
  'IsAvailable',
  'recommendations_buckets',
  'older_90_days',
];

export const attributesToRetrieve = [
  'user_id',
  'uuid',
  'name',
  'skill_levels_taught',
  'profile_type',
  'recommendations',
  'genres',
  'association_list',
  'languages',
  'instruments',
  'age_taught',
  'locations',
  'avatar_path',
  'cover_image',
  'pricing',
  'username',
  '_geoloc',
];
