const EN_TO_DE = {
  'Our Offers': 'Unsere Angebote',
  'within 60km': 'im Umkreis von 60km',
  'within 40km': 'im Umkreis von 40km',
  'within 20km': 'im Umkreis von 20km',
  'We are happy to help you by phone or e-mail!': 'Wir helfen dir gerne per Telefon oder via E-Mail',
  'SEND US AN E-MAIL': 'SCHREIB UNS',
  'Customer Success Manager': 'Customer Success Manager',
  'Vanessa-Naomi Moëlla': 'Vanessa-Naomi Moëlla',
  'Show map': 'Karte anzeigen',
  Search: 'Suchen',
  'Select your location': 'Wähle deinen Unterrichtsort aus',
  'Find music lessons near you...': 'Musikunterricht in deiner Nähe finden...',
  'Then let us know right away.': 'Dann lass es uns wissen.',
  'Would you like to get notified when teachers in your area become available?':
    'Möchtest du benachrichtigt werden, sobald eine Lehrperson in deiner Nähe verfügbar wird?',
  'Couldn’t find a teacher near you?': 'Keine Lehrperson gefunden in deiner Nähe?',
  'SIGN UP TO TEACH': 'ALS LEHRPERSON REGISTRIEREN',
  'Please enter a valid e-mail address': 'Bitte eine gültige E-Mailadresse eingeben',
  'Your e-mail address': 'E-Mail',
  'Enter your ZIP code': 'Postleitzahl eingeben',
  'Select your instrument': 'Musikinstrument auswählen',
  'NOTIFY ME': 'BENACHRICHTIGE MICH',
  'Search request sent!': 'Suchauftrag abgeschickt!',
  'Thank you for your message!': 'Danke für deine Nachricht!',
  'Your message has been sent.': 'Deine Nachricht wurde gesendet.',
  'You will hear from us shortly.': 'Wir melden uns in Kürze bei dir.',
  'Notify me': 'Abschicken',
  'Have questions or need support?': 'Hast du Fragen oder brauchst du Unterstützung?',
  'Sign up to teach': 'Als Lehrperson registrieren',
  'Log in': 'Einloggen',
  '+41 44 516 89 65': '+41 44 516 89 65',
  '+41 78 906 98 47': '+41 78 906 98 47',
  '+41 44 203 95 51': '+41 44 203 95 51',
  'We’re happy to support you personally. Call us, write us an email or find answers to your questions in our Help Centre.':
    'Wir unterstützen dich gerne persönlich. Ruf uns an, schreib uns eine E-Mail oder finde Antworten auf deine Fragen in unserem Hilfe-Center.',
  'Show more': 'Mehr anzeigen',
  'show more': 'mehr anzeigen',
  'View all': 'Alle ansehen',
  'About me': 'Über mich',
  Gallery: 'Galerie',
  Locations: 'Unterrichtsorte',
  Courses: 'Kurse',
  courses: 'kurse',
  Experience: 'Erfahrung',
  Education: 'Ausbildung',
  About: 'Über',
  More: 'Mehr',
  Awards: 'Auszeichnungen',
  Recordings: 'Aufnahmen',
  Performances: 'Auftritte',
  Languages: 'Sprachen',
  'Main musical genres': 'Wichtigste Musikrichtungen',
  'Skill levels taught': 'Unterrichtete Fähigkeitsstufen',
  Kids: 'Kinder',
  Advanced: 'Fortgeschrittene',
  Beginner: 'Anfänger*innen',
  Intermediate: 'Erfahrene',
  Professional: 'Profis',
  'Share this page': 'Seite teilen',
  'All recommendations are from verified students of this music teacher':
    'Alle Empfehlungen stammen von verifizierten Schüler*innen dieser Lehrperson auf Matchspace Music',
  All: 'Alle',
  Less: 'Weniger',
  'Private lesson': 'Privatunterricht',
  'Group courses': 'Gruppenunterricht',
  'Group course': 'Gruppenkurs',
  Workshops: 'Workshops',
  Workshop: 'Workshop',
  'Music camps': 'Music Camps',
  'Music camp': 'Music Camp',
  'Course details': 'Kursdetails',
  'About this course': 'Über diesen Kurs',
  'Total price': 'Gesamtpreis',
  'Subscription discount': 'Rabatt für Abo',
  'Trial subscription discount': 'Rabatt für Probe-Abo',
  saved: 'gespart',
  'View course details': 'Kursdetails ansehen',
  'Select lesson duration:': 'Lektionsdauer auswählen:',
  'Select lesson subscription:': 'Abo auswählen:',
  'mins.': 'Min.',
  lessons: 'Lektionen',
  Lessons: 'Lektionen',
  'Age group': 'Altersgruppe',
  'Select course': 'Kurs auswählen',
  'Choose an option': 'Option auswählen',
  'Leave us a note': 'Sende uns eine Nachricht',
  Directions: 'Wegbeschreibung',
  Present: 'heute',
  'Your message': 'Deine Nachricht',
  'Your contact details are required so that the teacher can get in touch with you.':
    'Deine Kontaktdaten werden benötigt, damit die Lehrkraft auf deine Anfrage antworten kann.',
  'First name': 'Vorname',
  Email: 'Email',
  'Mobile number': 'Mobilnummer',
  Zip: 'Postleitzahl',
  'I accept the': 'I akzeptiere die',
  'terms and conditions': 'Nutzungsbedingungen',
  'Invalid e-mail': 'Ungültige E-mail',
  Required: 'Pflichtfeld',
  Back: 'Zurück',
  'Maximum of 300 characters exceeded': 'Maximum von 300 Zeichen überschritten',
  Attention: 'Achtung',
  'If you delete your request, it will not be saved.': 'Deine Anfrage wird nicht gespeichert, wenn du diese löschst.',
  Delete: 'Löschen',
  Next: 'Weiter',
  Continue: 'Weitermachen',
  'Fully booked': 'Ausgebucht',
  by: 'von',
  'Configure your session': 'Konfiguriere deinen Unterricht',
  Take: 'Lerne',
  'lessons with': 'unterricht mit',
  in: 'in',
  or: 'oder',
  and: 'und',
  for: 'für',
  Adults: 'Erwachsene',
  Online: 'Online',
  'View less': 'Weniger anzeigen',
  'Link copied!': 'Link kopiert!',
  Filters: 'Filtern',
  'Course types': 'Kurs Typ',
  'Reset all': 'Zurücksetzen',
  Cancel: 'Abbrechen',
  results: 'Ergebnisse',
  Show: 'Anzeigen',
  'Home visits': 'Hausbesuche',
  'Home visit': 'Hausbesuche',
  "The lessons take place at the teacher's location.": 'Der Unterrichtet findet bei der Lehrperson statt.',
  'Lessons are online': 'Du nimmst Online-Unterricht',
  Studios: 'Studios',
  "Lessons take place at the teacher's location": 'Der Unterrichtet findet bei der Lehrperson statt.',
  'Regular rate': 'Regulärer Tarif',
  'Incl. teenagers and young adults in education': 'Inkl. Jugendliche und junge Erwachsene in Ausbildung',
  'Please contact': 'Bitte kontaktiere',
  'to verify their availability': 'um die Verfügbarkeit zu überprüfen',
  from: 'ab',
  Studio: 'Studio',
  'Tell us more about your search': 'Sag uns, was du suchst.',
  'lessons of': 'Lektionen à',
  From: 'Ab',
  'Music Education': 'Musikalische Ausbildung',
  'Musical Experience': 'Musikalische Erfahrung',
  'To checkout': 'Zur Kasse',
  'Select studio': 'Studio auswählen',
  'Choose your most convenient lesson location': 'Wähle den für dich am besten geeigneten Unterrichtsort',
  'Contact teacher': 'Lehrperson kontaktieren',
  'Age groups taught': 'Unterrichtete Altersgruppen',
  'View prices': 'Preise ansehen',
  'Show less': 'Weniger anzeigen',
  Recommendations: 'Empfehlungen',
  Recommendation: 'Empfehlung',
  'Student recommendation': 'Empfehlung von Schüler*innen',
  // Сheck translation
  ' or ': ' oder ',
  Location: 'Unterrichtsort',
  'Home visit': 'Hausbesuche',
  'Teacher’s studio': 'Studio',
  'Continue to booking': 'Weiter zur Buchung', // 'Bitte um Buchung',
  '* The trial subscription is only available once.': '* Das Probe-Abo ist nur einmalig verfügbar',
  'Send message to teacher': 'Nachricht an Lehrperson senden',
  'Please fill in all required fields': 'Bitte fülle alle geforderten Felder aus',
  'Customer Success': 'Kundenservice',
  Send: 'Senden',
  'Online lessons': 'Online-Unterricht',
  'Invalid email': 'Ungültige E-Mail',
  'terms & conditions': 'Nutzungsbedingungen',
  'Thank you!': 'Herzlichen Dank!',
  'You will hear from the teacher shortly.': 'Sie werden in Kürze vom Lehrer hören.',
  'Your message will not be saved': 'Deine Nachricht wird nicht gespeichert',
  'Your message will not be saved if you abort the process.':
    'Deine Nachricht wird nicht gespeichert, wenn du den Prozess abbrichst.',
  'CANCEL REQUEST': 'ANFRAGE ABBRECHEN',
  'lessons ': 'unterricht ',
  'Configure session': 'Jetzt buchen',
  'Certified Teacher': 'Zertifizierte Lehrkraft',
  'Teacher in Education': 'Lehrperson in Ausbildung',
  'Qualified Musican': 'Qualifizierte*r Musiker*in',
  'Certified Musician': 'Zertifizierte*r Musiker*in',
  'Lessons take place at your home': 'Unterricht findet bei dir zuhause statt',
  'Lessons take place online': 'Unterricht findet online statt',
  'Lessons take place at the teacher’s studio': 'Unterricht findet im Studio der Lehrperson statt',
  'Help centre': 'Hilfe-Center', // 'Häufig gestellte Fragen lesen',
  'Show list': 'Liste anzeigen',
  'Age groups': 'Altersgruppen',
  'Search in this area': 'In diesem Bereich suchen',
  'Total surcharge': 'Total Wegpauschale',
  'Travel surcharge': 'Wegpauschale',
  'All recommendations are from verified students of this music teacher on Matchspace Music':
    'Alle Empfehlungen stammen von verifizierten Schüler*innen dieser Lehrperson auf Matchspace Music',
  'Certified Music Teacher': 'Zertifizierte Lehrkraft',
  'Qualified Musician': 'Qualifizierte*r Musiker*in',
  'Student recommendations': 'Empfehlungen von Schüler*innen',
  'Private lessons': 'Privatunterricht',
  'LOADING...': 'LÄDT...',
  min: 'Min.',
  'Please select a studio address': 'Bitte wähle eine Studioadresse aus',
  'Search in this area': 'In diesem Bereich suchen',
  'Invalid mobile number': 'Ungültige Telefonnummer',
  'Last Name': 'Nachname',
  'View money back guarantee': 'Geld-zurück-Garantie ansehen',
  Teachers: 'Lehrpersonen',
  of: 'von',
  'All Online teachers': 'Alle Online-Lehrkräfte',
  'Expand search to include teachers offering online lessons from any location.':
    'Erweitere die Suche auf Lehrkräfte, die von jedem Ort aus Online-Unterricht.',
  'Skill level': 'Fähigkeitsstufe',
  'Lesson Duration': 'Lektionsdauer',
  '30 min.': '30 Min.',
  '45 min.': '45 Min.',
  '60 min.': '60 Min.',
  '90 min.': '90 Min.',
  'Skill level taught': 'Unterrichtete Fähigkeitsstufe',
  'Learn the fundamentals for starters': 'Lerne die Grundlagen für Einsteiger',
  'Expand your knowledge': 'Erweitere deine Kentnisse',
  'Master complex pieces': 'Meistere komplexe Stücke',
  'Train at the highest level': 'Trainiere auf Spitzenniveau',
  'Each lesson lasts 30 minutes.': 'Jede Unterrichtslektion dauert 30 Min.',
  'Each lesson lasts 45 minutes.': 'Jede Unterrichtslektion dauert 45 Min.',
  'Each lesson lasts 60 minutes.': 'Jede Unterrichtslektion dauert 60 Min.',
  'Each lesson lasts 90 minutes.': 'Jede Unterrichtslektion dauert 90 Min.',
  'You’ll be contacted shortly by the teacher.': 'Du wirst in Kürze von der Lehrperson kontaktiert.',
  'Available Languages': 'Verfügbare Sprachen',
  'CHECK AVAILABILITY': 'ANFRAGEN',
  'Thank you for your request': 'Vielen Dank für deine Anfrage',
  'Your request has been forwarded to your teacher, who will get in touch with you very shortly.':
    'Deine Anfrage wurde an deiner Lehrperson weitergeleitet, die sich in Kürze mit dir in Verbindung setzen wird.',
  "What's next?": 'Wie geht es weiter?',
  'The teacher will confirm their availability to teach you and reply to your message':
    'Die Lehrkraft wird bestätigt, dass sie für den Unterricht zur Verfügung steht und antwortet dir',
  'You can book the desired lesson subscription': 'Du kannst das gewünschte Unterrichts-Abo direkt buchen',
  'Your teacher will contact you to schedule your first lesson':
    'Deine Lehrkraft wird sich mit dir in Verbindung setzen, um Ihre erste Lektion zu vereinbaren',
  'You are in good hands': 'Du bist in guten Händen',
  'All our teachers are qualified and verified.': 'Alle unsere Lehrer*innen sind qualifiziert und geprüft.',
  'On top, you benefit from a unique trial lesson with a money-back guarantee.':
    'Darüber hinaus profitierst du von einer einzigartigen Probelektion mit Geld-zurück-Garantie.',
  'Trial lesson with money-back guarantee': 'Probelektion mit Zufriedenheitsgarantie',
  'Thank you!': 'Herzlichen Dank!',
  'Many thanks for your request! We have received your call back request and will contact you shortly.':
    'Vielen Dank für deine Nachricht! Wir haben deine Rückruf-Anfrage erhalten und melden uns schnellstmöglich bei dir.',
  'Teacher could not be found': 'Dieser Link ist nicht mehr verfügbar',
  'We are happy to help you via e-mail!': 'Wir helfen dir gerne via E-Mail',
  'We’re happy to support you personally. Write us an email or find answers to your questions in our Help Centre.':
    'Wir unterstützen dich gerne persönlich. Schreib uns eine E-Mail oder finde Antworten auf deine Fragen in unserem Hilfe-Center.',
  'Let us know what you are looking for and we are going to support you.':
    'Teile uns mit, wonach du suchst und wir unterstützen dich gerne.',
  'No suitable INSTRUMENT TEACHER found ?': 'Kein passender INSTRUMENTENLEHRER gefunden ?',
  "Didn't find a matching teacher?": 'Keine passende Lehrperson gefunden?',
  'We support you in finding a suitable INSTRUMENT teacher':
    'Wir unterddtutzen dich bei Suche nach einer passenddedn INSTRUMENT lehrerin',
  'CHAT WITH ME': 'CHATTE MIT MIR',
  'Thank you for your patience!': 'Danke für deine Geduld!',
  'We will get back to you with an update as soon as we hear back from your teacher.':
    'Wir melden uns schnellstmöglich bei dir, sobald wir mit der Lehrperson in Kontakt treten konnten.',
  'Thank you!': 'Herzlichen Dank!',
  'Many thanks for your request! We have received your call back request and will contact you shortly.':
    'Vielen Dank für deine Nachricht! Wir haben deine Rückruf-Anfrage erhalten und melden uns schnellstmöglich bei dir.',
  'Music Associations': 'Musikverbände',
  Associations: 'Verbände',
  'Customer Success Manager': 'Kundenbetreuung',
  'Customer Success': 'Kundenbetreuung',
  'Need support?': 'Brauchst du Unterstützung?',
  'I need help finding a teacher': 'Ich benötige Hilfe bei der Suche',
  'Available musical genres': 'Verfügbare Musikrichtungen',
  'The exact address will be communicated to you before your first lesson':
    'Die genaue Adresse wird dir vor der ersten Lektion kommuniziert',
  home: 'hausbesuche',
  'at the Studio': 'im Studio',
  'GET HELP': 'ANFRAGE STARTEN',
  'START SEARCH': 'ANFRAGE STARTEN',
  'Show More': 'Mehr anzeigen',
  // organization data
  'WRITE US': 'SCHREIB UNS',
  'CALL US': 'RUF UNS AN',
  TEACHERS: 'LEHRPERSONEN',
  'VIEW PROFILE': 'PROFIL ANSEHEN',
  Instrument: 'Instrument',
  'Age category': 'Altersgruppe',
  'All ages': 'Alle Altersgruppen',
  results: 'Resultate',
  Reviews: 'Bewertungen',
  'Get in touch': 'Kontakt aufnehmen',
  'Contact the teacher and learn more about lessons.': 'Mit der Lehrperson in Kontakt treten und Fragen stellen.',
  'Sign up': 'Anmelden',
  'Secure your spot and sign-up for lessons.': 'Sichere dir deinen Platz und melde dich an.',
  'Start lessons': 'Unterricht beginnen',
  'Get started with your unforgettable musical adventure.': 'Beginne dein unvergessliches musikalisches Abenteuer.',
  'About me': 'Über mich',
  'Teaching locations': 'Standorte für Unterricht',
  'My lessons': 'Mein Unterricht',
  'My specialization': 'Meine Spezialisierung',
  'Course type': 'Kurstyp',
  'Starting from': 'Angebote ab',
  CHF: 'CHF',
  for: 'für',
  'MORE DETAILS': 'MEHR INFOS',
  DETAILS: 'MEHR INFOS',
  'Group lessons': 'Gruppenunterricht',
  'Ensemble lessons': 'Ensembleunterricht',
  'Teacher details': 'Lehrperson-Details',
  'Offers for kids': 'Angebote für Kinder',
  'Offers for adults': 'Angebote für Erwachsene',
  'Teaching locations': 'Standorte für Unterricht',
  'Prices and offers': 'Preise und Angebote',
  'About course': 'Über den Kurs',
  'Lesson locations': 'Standorte für Unterricht',
  'LEARN MORE': 'MEHR ERFAHREN',
  'music teachers and schools': 'Lehrpersonen und Schulen',
  'At school location': 'Am Standort der Schule',
  'Get in touch with us': 'Nimm jetzt mit uns Kontakt auf',
  'We will get back to you as soon as possible. Many thanks.':
    'Wir kontaktieren dich so schnell wie möglich. Herzlichen Dank.',
  'Your data is protected and will not be shared with third parties.':
    'Deine Daten sind sicher und werden nicht mit Dritten geteilt.',
  SEND: 'ABSCHICKEN',
  'Other Locations': 'Mehr Standorte',
  'More Locations': 'Mehr Standorte',
  'Learn more about our offers for music students at our other locations in Zurich Oberland.':
    'Erfahre jetzt mehr über die Angebote für Musikschüler*innen an unseren diversen Standorten im Zürcher Oberland.',
  Instruments: 'Instrumente',
  'Discover all our musical instruments and courses taught at Music School Zurich Oberland.':
    'Entdecke jetzt alle Musikinstrumente und Fächer, die an der Musikschule Zürcher Oberland unterrichtet werden.',
  Events: 'Veranstaltungen',
  'Public Music School': 'Öffentliche Musikschule',
  Young: 'Jung',
  'Lesson durations': 'Lektionsdauern',
  'Offers for': 'Angebote für',
  'More Instruments': 'Mehr Instrumente',
  'Musical genres': 'Musikrichtungen',
  'First Name': 'Vorname',
  'Last Name': 'Nachname',
  'E-mail': 'E-Mail',
  'Postal Code': 'Postleitzahl',
  'Phone number is required': 'Telefonnummer ist erforderlich',
  'Your message...': 'Deine Nachricht...',
  'We will contact you as soon as possible. Thank you very much.':
    'Wir kontaktieren dich so schnell wie möglich. Herzlichen Dank.',
  'First name is required': 'Vorname ist erforderlich',
  'Last name is required': 'Nachname ist erforderlich',
  'Email is required': 'E-Mail ist erforderlich',
  'Email is invalid': 'E-Mail ist ungültig',
  'Postal code is required': 'Postleitzahl ist erforderlich',
  'Your data is safe and will not be shared with third parties.':
    'Deine Daten sind sicher und werden nicht mit Dritten geteilt.',
  'String instruments': 'Streichinstrumente',
  'Keyboard instruments': 'Tasteninstrumente',
  'Wind instruments': 'Blasinstrumente',
  'Percussion instruments': 'Schlaginstrumente',
  'No other location found': 'Kein anderer Standort gefunden',
  'Courses not available': 'Kurse nicht verfügbar',
  'Teachers not available': 'Lehrer nicht verfügbar',
  'Instruments not found': 'Instrumente nicht gefunden',
  'Gallery data not found': 'Galeriedaten nicht gefunden',
  'Event data not found': 'Ereignisdaten nicht gefunden',
  'Price configuration details': 'Details zur Preiskonfiguration',
  Weekly: 'Wöchentlich',
  'school in': 'Schule in',
  'These are the instruments we teach in our locations. Select the Instruments you are interested in to see all courses:':
    'Dies sind die Instrumente, die wir an unseren Standorten unterrichten. Wählen Sie die Instrumente aus, die Sie interessieren, um alle Kurse anzuzeigen:',
  'for all ages': 'für alle Altersgruppen',
  'for kids and young adults': 'für Kinder und Jugendliche',
  'for Adults': 'für Erwachsene',
  'Open in new window': 'In neuem Fenster öffnen',
  'Main building': 'Hauptgebäude',
  'Second building': 'Zweites Gebäude',
  'Description not found': 'Beschreibung nicht gefunden',
  'Find an offer': 'Angebot finden',
  'Find the right course or teacher.': 'Finde den richtigen Kurs oder die passende Lehrer*in.',
  'Secure your spot and register with a few clicks.': 'Sichere dir deinen Platz und melde dich mit wenigen Klicks an.',
  'Begin your unforgettable musical adventure.': 'Beginne dein unvergessliches musikalisches Abenteuer.',
  'Age groups thought': 'Altersgruppen',
  'Main musical genres': 'Wichtigste Musikrichtungen',
  'INSTRUMENT lessons': 'INSTRUMENT Unterricht',
  'All Instruments': 'Alle Instrumente',
  Private: 'Privat',
  'All age groups': 'Alle Altersgruppen',
  'for adults': 'für Erwachsene',
  'All courses': 'Alle Kurse',
  'Private lessons': 'Privatunterricht',
  'for kids': 'für Kids',
  'SIGN UP': 'ANMELDEN',
  instrument: 'instrumente',
  'Music lessons': 'Musikunterricht',
  'Lesson frequencies': 'Lektionsfrequenzen',
  'VIEW COURSES': 'KURSE ANSEHEN',
  'How it works': 'So funktioniert es',
  'The prices quoted are indicative and may change according to the course configuration and possible subsidization after registration.':
    'Die angegebenen Preise sind indikativ und können sich entsprechend der Kurskonfiguration und bei einer möglichen Subventionierung nach der Anmeldung ändern.',
  'Find your course': 'Kurs finden',
  lesson: 'Lektion',
  'Course information': 'Kursinformationen',
  Learn: 'Lerne',
  'No Location Found': 'Kein Standort gefunden',
  'No teacher details found': 'Keine Lehrerdetails gefunden.',
  'Other skills': 'Andere Fähigkeiten',
  'Music instruments': 'Musikinstrumente',
  'Other musical subjects': 'Sonstige Musikfächer',

  'Your message here...': 'Your message here...',
  'Contact details can be entered in the next step.': 'Kontaktdetails können im nächsten Schritt eingegeben werden.',
  CONTINUE: 'WEITER',
  CANCEL: 'ABBRECHEN',
  "I'm looking for": 'Ich suche',
  'The lessons are for': 'Der Unterricht ist',
  'myself.': 'für mich.',
  'my child.': 'mein Kind.',
  'somebody else.': 'für eine andere Person.',
  'Preferred location is/are': 'Bevorzugter Unterrichtsort ist/sind',
  'at your studio.': 'in deinem Studio.',
  'at my home.': 'bei mir zuhause.',
  'live-online.': 'live-online.',
  'in specific location(s):': 'An spezifische(n) Orte(n):',
  'flexible.': 'flexibel.',
  'The skill level is': 'Die Fähigkeitsstufe ist',
  'beginner.': 'Anfänger*in.',
  'advanced.': 'fortgeschritten.',
  'professional.': 'professionell.',
  'The availability is': 'Meine Verfügbarkeit ist',
  // 'quite flexible.': 'sehr flexibel.',
  'on specific days during the week.': 'an einem spezifischen Tag.',
  'not defined yet.': 'noch nicht sicher.',
  'irregular.': 'unregelmässig.',
  'Preferred lesson hours are': 'Bevorzugte Unterrichtszeiten sind',
  'in the morning.': 'am Morgen.',
  'over lunch.': 'über Mittag.',
  'in the afternoon.': 'am Nachmittag.',
  'in the evening.': 'am Abend.',
  'quite flexible.': 'ziemlich flexibel.',
  'at specific times: ': 'an spezifischen Zeiten:',
  'I want to start': 'Gewünschter Unterrichtsstart ist',
  'The ideal start date is': 'Gewünschter Unterrichtsstart ist',
  'as soon as possible.': 'so schnell wie möglich.',
  'in a few weeks.': 'in ein paar Wochen.',
  'in a specific month.': 'in einem Monat.',
  'on a specific day:': 'an einem spezifischen Tag nämlich:',
  'Lessons should be': 'Lektionen vorzugsweise',
  'once a week.': 'einmal pro Woche.',
  'once every two weeks.': 'einmal alle zwei Wochen.',
  'once a month.': 'einmal im Monat.',
  'flexibly agreed.': 'flexibel vereinbart.',
  'Favorite genre is': 'Bevorzugte Genres sind',
  'classical.': 'klassische Musik.',
  'pop & rock.': 'Pop-Musik.',
  'folk.': 'Volksmusik.',
  'various.': 'vielseitig.',
  'flexible.': 'flexibel.',
  'as followed:': 'wie folgt:',
  'The learning objective is': 'Mein Ziel ist es',
  'to learn something new.': 'etwas Neues zu lernen.',
  'to improve my current skills.': 'meine Fähigkeiten zu verbessern.',
  'to become a pro.': 'ein Profi zu werden.',
  'to prepare for an exam.': 'mich auf eine Prüfung vorzubereiten.',
  'as followed:': 'wie folgt:',
  'Preferred lesson duration is': 'Bevorzugte Lektionsdauer ist',
  '30 minutes.': '30 Minuten.',
  '45 minutes.': '45 Minuten.',
  '60 minutes.': '60 Minuten.',
  '90 minutes.': '90 Minuten.',
  'not yet defined.': 'noch nicht sicher.',
  'Preferred subscription size is': 'Bevorzugtes Lektionspaket ist',
  '5 lessons.': '5 Lektionen.',
  '10 lessons.': '10 Lektionen.',
  '20 lessons.': '20 Lektionen.',
  'not yet defined.': 'noch nicht sicher.',
  'An instrument': 'Ein Instrument',
  'is already available.': 'ist verfügbar.',
  'is not yet available but will be.': 'ist bald verfügbar.',
  'in the process of being bought.': 'wird gerade gekauft.',
  'is needed, help me!': 'wird gebraucht, ich benötige Hilfe.',
  'Complete later': 'Später abschliessen',
  'Are you sure you want to cancel?': 'Bist du sicher, dass du abbrechen möchtest?',
  Submit: 'Abschicken',
  Cancel: 'Abbrechen',
  'My desired instrument is': 'Mein Wunschinstrument ist',
  'The person who will take lessons is': 'Der Unterricht ist für',
  'My skill level is': 'Meine Fähigkeitsstufe ist',
  'My availability is': 'Meine Verfügbarkeit ist',
  'Preferred lesson frequency is': 'Bevorzugte Lektionsfrequenz ist',
  'The instrument to be used is': 'Das zu verwendende Instrument ist',
  'mine and already available.': 'meins und bereits verfügbar.',
  'not yet available but will be.': 'bald verfügbar.',
  'not yet available but is in the process of being bought.': 'bald verfügbar (wird gerade gekauft).',
  'not available and is needed, please help me!': 'nicht verfügbar, ich benötige HIlfe!',
  'Complete later': 'Später abschliessen',
  'Enter your message...': 'Nachricht eingeben...',
  'Character limit exceeded': 'Zeichenlimit überschritten',
  'Thank you and best regards.': 'Herzlichen Dank und Grüsse.',
  'is available.': 'ist verfügbar.',
  'is soon available.': 'ist bald verfügbar.',
  'is not available. I need support.': 'ist nicht verfügbar. Ich brauche Unterstützung.',
  'jazz.': 'Jazz.',
  'Choose options': 'Optionen auswählen',
  'CONTACT ME': 'KONTAKTIERE MICH',
  'Music lessons are currently not available.' : 'Musikunterricht ist derzeit nicht verfügbar.',
  'Rental instrument available': 'Leihinstrument vorhanden',
  'Instrument details': 'Instrument-Details',
  'Get in touch' : 'Jetzt Kontakt aufnehmen',
  'Send me a message to get started with lessons.' : 'Sende mir eine Nachricht um mit dem Unterricht zu beginnen.',
  'Enter your message here...' : 'Gib hier deine Nachricht ein ...',
  '95% find their ideal teacher on the first try' : '95% finden ihre Lehrperson beim ersten Versuch',
  'Contact your teacher' : 'Kontaktiere deine Lehrperson',
  'Get in touch and ask any questions you have.' : 'Chatte mit deiner Lehrperson und erhalte Antworten auf deine Fragen.',
  'Schedule your first lesson' : 'Vereinbare deine Probelektion',
  'Agree on a date, time and location to get started with your lessons.' :'Vereinbare einen Termin für die erste Lektion um mit deinem Unterricht zu beginnen.',
  'Book your subscription' : 'Buche dein Abo',
  'Benefit from our money-back guarantee on your first lesson, simple as that.' : 'Profitiere von unserer Geld-zurück-Garantie für deine erste Lektion. So einfach ist das!',
  'Book now, pay later' : 'Jetzt buchen, später bezahlen',
  'Secure your slot for lessons today and pay later.' : 'Sichere dir heute deinen Platz für Unterricht und bezahle später',
  'Our flexible payment options' : 'Unsere flexiblen Zahlungsoptionen',
  'Pay in rates' : 'Ratenzahlung',
  "Don't have the full amount available in your account? Book your subscription today and pay in three interest-free rates with Klarna. Eligibility terms of the supplier apply." : "Du kannst nicht alles auf einmal bezahlen? Kein Problem! Buche dein Abo heute und bezahle in drei Zinsfreien Raten mit Klarna. Es gelten die Bedingungen des Anbieters.",
  'Trial lesson with satisfaction guarantee' : 'Probelektion mit Zufriedenheitsgarantie',
  'Book now, pay later' : 'Jetzt buchen, später bezahlen',
  'Do you need support?' : 'Brauchst du Unterstützung?',
};

const EN_TO_FR = {
  'Certified Musician': 'Musicien*ne certifié*e',
  'Teacher in Education': 'Enseignant*e en éducation',
  'Qualified Musician': 'Musicien*ne qualifié*e',
  'Certified Teacher': 'Enseignant*e certifié*e',
  Singing: 'Chant',
  'Vocal Coaching (Stimmbildung)': 'Formation vocale',
  Adults: 'Adultes', // Erwachsene
  Kids: 'Enfants', // Kinder
  Recommendation: 'Recommandation', // Empfehlungen
  Recommendations: 'Recommandations', // Empfehlungen
  and: 'et', // und
  or: 'ou',
  home: 'maison',
  studio: 'studio',
  online: 'en ligne',
};

const translateENtoDE = (words, language) => {
  if (language === 'ch-de') {
    return EN_TO_DE[words];
  }

  if (language === 'ch-fr') {
    return EN_TO_FR[words] || words;
  }

  return words;
};

const KEY_TO_EN = {
  home: 'Home visit',
  studio: 'at the Studio',
  kids: 'Kids',
  adults: 'Adults',
  advanced: 'Advanced',
  beginner: 'Beginner',
  intermediate: 'Intermediate',
  professional: 'Professional',
  online: 'Online',
  studios: 'Studio',
  student_place: 'Home visit',
  teacher_place: 'Studio',
  workshop: 'Workshops',
  music_camp: 'Music camps',
  pri_vate: 'Private lessons',
  group_course: 'Group courses',
  verified_talent: 'Teacher in Education',
  certified_teacher: 'Certified Music Teacher', // 'Certified Teacher',
  professional_musician: 'Qualified Musician', // 'Qualified Musican',
  certified_musician: 'Certified Musician',
};

const translateFieldKeyToEN = (key, language) => {
  return translateENtoDE(KEY_TO_EN[key], language);
};

export { translateENtoDE, translateFieldKeyToEN };
