export const enData = {
    "fname": "First name",
    "lname": "Last name",
    "phone": "Phone",
    "button": "SEND",
    "message": "Your message",
    "component": "signup-form-component",
    "job_title": "Job title",
    "company_name": "Comapany ",
    "email_address": "Email address",
    "success_message": "Thank you very much! We’ve received your details and will be in touch with you shortly.",
    "email_validation": "Email  is required",
    "fname_validation": "First name is required",
    "lname_validation": "Last name  is required",
    "phone_validation": "Phone  is required",
    "message_validation": "Message  is required",
    "job_title_validation": "Job title is  is required",
    "company_name_validation": "Company name is required",
    "email_validation_message": "Please enter a valid email",
    "titleForm": "Your contact information"
}

export const deData = {
    "id": "",
    "_uid": "5cf9ff4f-3a5d-46ab-85cd-7a11b0d9c2fa",
    "fname": "Vorname",
    "lname": "Nachname",
    "phone": "Telefonnummer",
    "button": "ABSCHICKEN ",
    "message": "Deine Nachricht",
    "component": "signup-form-component",
    "job_title": "Position",
    "company_name": "Firma",
    "email_address": "Emailadresse",
    "success_message": "Herzlichen Dank! Deine Angaben wurden erfolgreich übermittelt. Wir kontaktieren dich so schnell wie möglich.",
    "email_validation": "Emailadresse erforderlich",
    "fname_validation": "Vorname erforderlich",
    "lname_validation": "Nachname erforderlich",
    "phone_validation": "Telefonnummer erforderlich",
    "message_validation": "Nachricht erforderlich",
    "job_title_validation": "Position erforderlich",
    "company_name_validation": "Firmenname erforderlich",
    "email_validation_message": "Bitte geben Sie eine gültige E-Mail ein",
    "titleForm": "Deine Kontaktinformationen"
}